# todo
# - pipeline input, or simply a library variable, or simply assign a random number to an env var
# - branching
# - looping
# - extend another pipeline
# - build and deploy jobs (not really deploy anything)
#
# Leave it at the above for now.  I need to get onto other stuff as well.

#==================================================================================================

trigger: none
pr: none 

stages:
  - stage: checkout
    jobs:
      - job: checkout
        steps:
          - checkout: self
          - bash: echo 'some message here'
            name: checkout_here
  - stage: print_vars
    jobs:
      - job: print_vars
        steps:
          - bash: |
              pwd
              ls -la