# todo
# - pipeline input, or simply a library variable, or simply assign a random number to an env var
# - branching
# - looping
# - extend another pipeline
# - build and deploy jobs (not really deploy anything)
#
# Leave it at the above for now.  I need to get onto other stuff as well.

#==================================================================================================

trigger: none
pr: none 

resources:
  repositories:
    - repository: practice-azure-ado
      type: github
      name: brian-sigurdson/practice-azure-ado
      ref: refs/heads/main
      endpoint: brian-sigurdson


stages:
  - stage: print_vars
    jobs:
      - job: print_vars
        steps:
          - bash: |
              echo "$(buildProject)"
              echo "$(s3LogsUri)"